
INSERT INTO teams(team_name,rating) VALUES ('Arsenal FC',1673);
INSERT INTO teams(team_name,rating) VALUES ('Norwich City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Chelsea FC',1651);
INSERT INTO teams(team_name,rating) VALUES ('Oldham Athletic',1200);
INSERT INTO teams(team_name,rating) VALUES ('Coventry City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Middlesbrough FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Crystal Palace',1426);
INSERT INTO teams(team_name,rating) VALUES ('Blackburn Rovers',1200);
INSERT INTO teams(team_name,rating) VALUES ('Everton FC',1527);
INSERT INTO teams(team_name,rating) VALUES ('Sheffield Wednesday',1200);
INSERT INTO teams(team_name,rating) VALUES ('Ipswich Town',1200);
INSERT INTO teams(team_name,rating) VALUES ('Aston Villa',1548);
INSERT INTO teams(team_name,rating) VALUES ('Leeds United',1634);
INSERT INTO teams(team_name,rating) VALUES ('Wimbledon FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Sheffield United',1343);
INSERT INTO teams(team_name,rating) VALUES ('Manchester United',1705);
INSERT INTO teams(team_name,rating) VALUES ('Southampton FC',1423);
INSERT INTO teams(team_name,rating) VALUES ('Tottenham Hotspur',1608);
INSERT INTO teams(team_name,rating) VALUES ('Nottingham Forest',1200);
INSERT INTO teams(team_name,rating) VALUES ('Liverpool FC',1725);
INSERT INTO teams(team_name,rating) VALUES ('Manchester City',1799);
INSERT INTO teams(team_name,rating) VALUES ('Queens Park Rangers',1200);
INSERT INTO teams(team_name,rating) VALUES ('Swindon Town',1200);
INSERT INTO teams(team_name,rating) VALUES ('Newcastle United',1514);
INSERT INTO teams(team_name,rating) VALUES ('West Ham United',1626);
INSERT INTO teams(team_name,rating) VALUES ('Leicester City',1568);
INSERT INTO teams(team_name,rating) VALUES ('Bolton Wanderers',1200);
INSERT INTO teams(team_name,rating) VALUES ('Derby County',1200);
INSERT INTO teams(team_name,rating) VALUES ('Sunderland AFC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Barnsley FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Charlton Athletic',1200);
INSERT INTO teams(team_name,rating) VALUES ('Bradford City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Watford FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Fulham FC',1358);
INSERT INTO teams(team_name,rating) VALUES ('West Bromwich Albion',1380);
INSERT INTO teams(team_name,rating) VALUES ('Birmingham City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Portsmouth FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Wolverhampton Wanderers',1449);
INSERT INTO teams(team_name,rating) VALUES ('Wigan Athletic',1200);
INSERT INTO teams(team_name,rating) VALUES ('Reading FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Stoke City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Hull City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Burnley FC',1437);
INSERT INTO teams(team_name,rating) VALUES ('Blackpool FC',1200);
INSERT INTO teams(team_name,rating) VALUES ('Swansea City',1200);
INSERT INTO teams(team_name,rating) VALUES ('Cardiff City',1200);
INSERT INTO teams(team_name,rating) VALUES ('AFC Bournemouth',1200);
INSERT INTO teams(team_name,rating) VALUES ('Huddersfield Town',1200);
INSERT INTO teams(team_name,rating) VALUES ('Brighton & Hove Albion',1510);
